import { Button, Container, Grid, Typography } from "@mui/material";
import QRCode from "react-qr-code";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CurrencyPad from "../components/CurrencyPad";
import styles from "../styles/Home.module.css";
import React from "react";
import QRDisplay from "../components/QRDisplay";

const Home: NextPage = () => {
  const [showQR, setShowQR] = React.useState(false);
  const [amount, setAmount] = React.useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxWidth="sm">
          <Grid container direction="column">
            {showQR ? (
              <>
                <Grid sx={{ background: "white", padding: "16px" }} item>
                  <QRDisplay amount={amount} />
                </Grid>
                <Grid item>
                  <Button
                    fullWidth
                    variant="contained"
                    color="error"
                    onClick={() => setShowQR(false)}
                  >
                    Cancel
                  </Button>
                </Grid>
              </>
            ) : (
              <>
                <Grid item>
                  <CurrencyPad onInput={(a) => setAmount(a)} />
                </Grid>
                <Grid item xs>
                  <Button
                    onClick={() => setShowQR(true)}
                    variant="contained"
                    fullWidth
                    sx={{ minHeight: "64px" }}
                  >
                    Enter
                  </Button>
                </Grid>
              </>
            )}
          </Grid>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
